const MIN_SIDEBAR_WIDTH = 200;
const MIN_FILE_EXPLORER_WIDTH = 200;
const MAX_SIDEBAR_WIDTH = 800;
const DEFAULT_SIDEBAR_WIDTH = 350;
const DEFAULT_MAIN_SIZE = 1000;

export {
  DEFAULT_MAIN_SIZE,
  DEFAULT_SIDEBAR_WIDTH,
  MAX_SIDEBAR_WIDTH,
  MIN_FILE_EXPLORER_WIDTH,
  MIN_SIDEBAR_WIDTH,
  
  
};
